# Generated by Django 4.0.4 on 2022-05-05 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElementForEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=50)),
                ('folderWithGLTFModel', models.FileField(blank=True, default=None, upload_to='')),
            ],
            options={
                'verbose_name': 'Элемент Экипировки(содержание)',
                'verbose_name_plural': 'Элементы Экипировки(содержание)',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ItemOfEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=25)),
                ('selectionЕlements', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ENGRAVING.elementforequipment')),
            ],
            options={
                'verbose_name': 'Элемент Экипировки',
                'verbose_name_plural': 'Элементы Экипировки',
                'ordering': ['id'],
            },
        ),
    ]
